ack.lang({
	'loading' : 'loading',
	'You need to be connected to the internet to use this widget' : 'You need to be connected to the internet to use this widget',
	'(Close)' : '(Close)',
	'Close' : 'Close',
	'Login' : 'Login',
	'login / logout' : 'login / logout',
	'Full terms of use available at': 'Full terms of use available at',
	'Logout' : 'Logout',
	'Anonymous' : 'Anonymous',
	'Login' : 'Login',
	'Sign up for free now! Some widgets offer extra features when you\'re signed in. They can save anything you create in the widget or send information to another service for you.' : 'Sign up for free now! Some widgets offer extra features when you\'re signed in. They can save anything you create in the widget or send information to another service for you.',
	'Back to Profile' : 'Back to Profile',
	'Username' : 'Username',
	'User' : 'User',
	'Email' : 'Email',
	'you@email.com' : 'you@email.com',
	'Password' : 'Password',
	'Signup' : 'Signup',
	'By registering you are agreeing to our terms of use' :'By registering you are agreeing to our terms of use',
	'You need to be online to register' :'You need to be online to register',
	'Please Complete' : 'Please Complete',
	'Username or Email' : 'Username or Email',
	'You need to be online to sign in' : 'You need to be online to sign in',
	'Later' : 'Later',
	'Unknown Error' : 'Unknown Error',
	'Interactive features provided by Bookry : http://bookry.com' : 'Interactive features provided by Bookry : http://bookry.com',
	'My Account' : 'My Account',
    'Updates for this widget have been found. Would you like to apply them now?' : 'Updates for this widget have been found. Would you like to apply them now?',
    "Updates available" : "Updates available",
    "Yes" : "Yes",
    "No" : "No",
    "Okay" : "Okay"
});
